# Generated by Django 3.1.7 on 2021-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('counter', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=16)),
            ],
        ),
    ]
